# METZ:
# "The knowledge that rims are at [0] should not be duplicated; it should be known in just one place."
# "these few lines of code are a minor inconvenience compared to the permanent cost of repeatedly indexing into a complex array"
# "If you rephrase every one of [a class's] methods as a question, asking the question ought to make sense."

# BOWLING SIMULATOR WITH SCORING DONE FRAME-BY-FRAME (vs. 'kata' version)
# second attempt - trying to design by proper classes/object-orientation
# will write as single-player, then add back multiplayer/skill weights
# but:  first thought -
# the basic units/tasks here might be:
#   roll / select result from input range
#   frame / store some number of rolls, give total/bonus
#     frame-tenth / same, w/ special cases
#   player-turn / create and fill one frame
#   player-game / link ten frames to represent complete game
#   player / (only need if skill or if multiple? not sure)
#   game / directs turns/games and evaluate scores/winners

# crux of trouble so far:  a LANE_GAME is built out of turns, but a PLAYER_GAME is built out of consecutive frames, w/ scores
# should frame data get stored in PLAYER?  that would require TURN to distribute FRAMES among PLAYERS

# ---- MESSAGES ----
# who's playing?
# what frame are we in?
# whose turn is it?
# what roll result/frame result? --> how good is player?
# what's the current score? --> who's the current leader?
# is the game over?
# who won?


# FRAME AND ROLLCALC SPLIT WAS GENERATED BY TESTING NEEDS. DOES THAT MAKE SENSE?
  # -->  okay, so : nothing changed; only way to test fixed cases is to inject Frame with predetermined Rolls
  # this requires accessor inside class, which seems like a problem  
  # or else is this the wrong place to have that method?
  # also: if-statement looks like it might be a no-no



puts; puts


# ---------------------------------------------------------
# returns up to two weighted random rolls from 10 initial pins
class RollCalc
  attr_reader :results  

  def initialize(skill = 0)  #add player skill here later?
    raise RangeError unless skill >= 0
    @skill = skill
    @roll_no = 1
    @pins_standing = 10
    @results = []
    weighted_roll(@pins_standing)
  end
  
  private
  
  def weighted_roll(pins)
    picks = []
    (@skill + 1).times do 
      pick = rand(0..pins)
      picks << pick
      break if pick == pins
    end
    pins_hit = picks.max
    @results << pins_hit
    @roll_no += 1
    @pins_standing -= pins_hit
    weighted_roll(@pins_standing) unless pins_hit == 10 || @roll_no > 2
  end
  
 # BECAUSE UNIT-TESTING CURRENT VERSION OF FRAME IS TRICKY:
# am I sure sure that roll is a class? because for now roll doesn't 'implement new_roll', it implements *result* -- which isn't really implementing anything
# should it be Lane? or Roller? so that instead of Roll.new.result (where result is just a reader),
# you would inject Roller.new, and expect it to implement roll and roll(pins)?
# except at that point, Roller sounds an awful lot like what you'd call a "frame" in actual bowling --
# its data consists of pins, and its behavior consists of hitting/counting them
 
end



# METZ: "Gear no longer cares about the class of the injected object, it merely expects that it implement diameter."
# ---------------------------------------------------------
# stores a set of rolls in an array
class Frame
  attr_reader :results  # need like this to rig frames for testing -- seems like a problem
 
  def initialize(roll_results)
    @results = roll_results
  end
  
  def total
    @results.reduce(:+)
  end

  def strike?
    @results[0] == 10
  end
  
  def spare?
    strike? == false && total == 10
  end
end
# 10th frame with [10, 0, 10] and [10, 0, 0] will be good test cases...
class FrameTen < Frame  # a full, unique frame might not be best way to handle this...save for now
    
  def spare?  # good for testing override; but would this ever be necessary?
    strike? == false && (@frame[0] + @frame[1]) == 10
  end
end


# okay wait so : nothing changes when you bring roll generation into Frame
#   to hard-wire a strike or spare during testing, :results has to be an accessor
#   is it the class or the testing approach that needs to change?
#   choice will affect whether frame needs to be able to pass skill info on to Roller
class FrameIncludingRolls
  attr_reader :results   # will this be necessary?  maybe just to pass array up a level...
 
  def initialize(skill = 0)
    raise RangeError unless skill >= 0
    @skill = skill
    @roll_no = 1
    @pins_standing = 10
    @results = []
    weighted_roll(@pins_standing)
  end

  def first_roll
    @results[0]
  end
  
  def second_roll
    @results[1] # this doesn't appear to require an 'unless' -- simply returns nil if nothing there
  end           # could add boolean second_roll? but don't see value yet
    
  def total
    @results.reduce(:+)
  end

  def strike?
    @results[0] == 10
  end
  
  def spare?
    strike? == false && total == 10
  end

  private
  
  def weighted_roll(pins)
    picks = []
    (@skill + 1).times do 
      pick = rand(0..pins)
      picks << pick
      break if pick == pins
    end
    pins_hit = picks.max
    @results << pins_hit
    @roll_no += 1
    @pins_standing -= pins_hit
    weighted_roll(@pins_standing) unless pins_hit == 10 || @roll_no > 2
  end
end


10.times do
  puts "FrameIncludingRolls"
  test_fr = FrameIncludingRolls.new
  puts test_fr.inspect
  puts test_fr.results.inspect
  puts test_fr.first_roll
  puts test_fr.second_roll           # no error w/ strike, just blank
  puts test_fr.second_roll.inspect   # yes, nil
  puts test_fr.total
  puts test_fr.strike?
  puts test_fr.spare?
  puts
end



class Player
  attr_reader :skill, :frames
  
  def initialize(skill = 0)
    @skill = skill
    @frames = []
    @scores = []
  end
  
  def bowl
    player_frame = Frame.new(@skill).results
    @frames << player_frame
  end
end


class Turn
  def initialize(players)
    @players = players
    @players.each { |player| player.bowl }
    @players.each { |player| puts player.frames.inspect }
    puts
  end
end


class Game
  attr_reader :players # :winner
  
  def initialize(num_players)
    @players = []
    num_players.times { @players << Player.new }
  end
  
  def play_game
    10.times { Turn.new(@players) }
  end
end


# puts "bob"
# bob = Player.new
# bob.bowl
# puts bob.frames.inspect
# 9.times { bob.bowl }
# puts bob.frames.inspect

# puts "turns"
# alpha = Player.new
# beta = Player.new
# 10.times do 
  # turn = Turn.new [alpha, beta]
# end

# puts "test game"
# test_game = Game.new(3)
# test_game.play_game



# ===================================================================================================================================================================
# METZ "test everything just once and in the proper place"
require "test/unit"

class TestRollCalc < Test::Unit::TestCase
  def test_roll_limits
    roll = RollCalc.new
    assert roll.results.max <= 10
    assert roll.results.min >= 0
  end
  
  def test_roll_sum
    roll = RollCalc.new
    assert roll.results.reduce(:+).between? 0, 10
  end
    
  def test_roll_sum_skill
    skill = 15
    roll = RollCalc.new(skill)
    assert roll.results.reduce(:+).between? 0, 10
  end
end


class TestFrame < Test::Unit::TestCase
    
  def test_frame_total
    frame = Frame.new [3,4]
    assert frame.total == 7
  end
  
  def test_frame_strike
    frame = Frame.new [10]
    assert frame.strike?      
  end 
  
  def test_frame_spare
    frame = Frame.new [1,9]
    assert frame.spare?
  end
end



# for understanding structure of object
def roll_tests_temp
  puts "roll_tests line #{__LINE__}"
  roll1 = Roll.new
  puts "this is object: #{roll1}"
  puts "this is reading result w/in object: #{roll1.result} / no change between readings: #{roll1.result}"
  roll2 = Roll.new.result
  puts "this is result of new object saved to var: #{roll2}"
  puts
end

